# Generated by Django 3.2.21 on 2023-09-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False)),
                ('mailid', models.CharField(db_column='MailID', max_length=40)),
                ('query', models.TextField(db_column='Query')),
                ('query_type', models.CharField(db_column='Query_type', max_length=10)),
            ],
        ),
    ]
