# Generated by Django 3.2.21 on 2023-09-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_queries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='query_type',
            field=models.CharField(db_column='Query_type', max_length=50),
        ),
    ]
