# Generated by Django 3.2.21 on 2023-09-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mailid',
            field=models.EmailField(db_column='MailID', max_length=254, primary_key=True, serialize=False),
        ),
    ]
